using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Testing;
using Parlance.CSharp.Analyzers.Rules;
using Verify = Microsoft.CodeAnalysis.CSharp.Testing.CSharpAnalyzerVerifier<
    Parlance.CSharp.Analyzers.Rules.PARL3001_CognitiveComplexityThreshold,
    Microsoft.CodeAnalysis.Testing.DefaultVerifier>;

namespace Parlance.CSharp.Tests.Rules;

public sealed class PARL3001Tests
{
    [Fact]
    public async Task NoDiagnostic_WhenComplexityEqualsThreshold()
    {
        var source = """
            class C
            {
                void M()
                {
                    for (var i = 0; i < 10; i++)
                    {
                        foreach (var item in "")
                        {
                            while (true)
                            {
                                do
                                {
                                    if (true)
                                    {
                                    }
                                } while (false);
                            }
                        }
                    }
                }
            }
            """;

        await Verify.VerifyAnalyzerAsync(source);
    }

    [Fact]
    public async Task Reports_WhenComplexityExceedsThreshold()
    {
        var source = """
            class C
            {
                void {|#0:M|}()
                {
                MyLabel:
                    for (var i = 0; i < 10; i++)
                    {
                        foreach (var item in "")
                        {
                            while (true)
                            {
                                do
                                {
                                    if (true)
                                    {
                                        goto MyLabel;
                                    }
                                } while (false);
                            }
                        }
                    }
                }
            }
            """;

        // Score breakdown under Parlance's hybrid goto rule (T4.5):
        //   for (+1) + foreach (+2) + while (+3) + do (+4) + if (+5)
        //   + goto at nesting 5 (+6) = 21.
        var expected = Verify.Diagnostic("PARL3001")
            .WithLocation(0)
            .WithSeverity(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
            .WithOptions(DiagnosticOptions.IgnoreAdditionalLocations)
            .WithArguments("M", 21, 15);

        await Verify.VerifyAnalyzerAsync(source, expected);
    }

    [Fact]
    public async Task NoDiagnostic_ForGeneratedCode()
    {
        var source = """
            // <auto-generated/>
            class C
            {
                void M()
                {
                MyLabel:
                    for (var i = 0; i < 10; i++)
                    {
                        foreach (var item in "")
                        {
                            while (true)
                            {
                                do
                                {
                                    if (true)
                                    {
                                        goto MyLabel;
                                    }
                                } while (false);
                            }
                        }
                    }
                }
            }
            """;

        await Verify.VerifyAnalyzerAsync(source);
    }

    [Fact]
    public async Task IncompleteSyntax_DoesNotThrowOrReport()
    {
        var source = """
            class C
            {
                void M(bool b)
                {
                    if (b)
                    {
                }
            }
            """;

        var expected = DiagnosticResult.CompilerError("CS1513")
            .WithSpan(8, 2, 8, 2);

        await Verify.VerifyAnalyzerAsync(source, expected);
    }

    [Fact]
    public async Task Reports_UsingEditorConfigThresholdOverride()
    {
        var source = """
            class C
            {
                void {|#0:M|}(bool b)
                {
                    if (b)
                    {
                    }
                    else
                    {
                    }
                }
            }
            """;

        var expected = Verify.Diagnostic("PARL3001")
            .WithLocation(0)
            .WithSeverity(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
            .WithOptions(DiagnosticOptions.IgnoreAdditionalLocations)
            .WithArguments("M", 2, 1);

        var test = new CSharpAnalyzerTest<
            Parlance.CSharp.Analyzers.Rules.PARL3001_CognitiveComplexityThreshold,
            DefaultVerifier>
        {
            TestCode = source,
        };

        test.TestState.AnalyzerConfigFiles.Add((
            "/.editorconfig",
            """
            root = true

            [*.cs]
            dotnet_code_quality.PARL3001.max_cognitive_complexity = 1
            """));
        test.ExpectedDiagnostics.Add(expected);

        await test.RunAsync();
    }

    /// <summary>
    /// PARL3001 encodes each cognitive-complexity increment into the diagnostic
    /// as a pair: the N-th <see cref="Diagnostic.AdditionalLocations"/> entry
    /// and the <c>increment.N.reason</c> property. A consumer decoding these
    /// two channels in parallel must reconstruct every increment's location
    /// and reason. This test exercises all three reason-string variants the
    /// metric emits — <c>"+1"</c>, <c>"+N (incl M for nesting)"</c>, and
    /// <c>"+1 (recursion)"</c> — on a single method so the wire format is
    /// locked down.
    /// </summary>
    [Fact]
    public async Task EncodesIncrementsAsAdditionalLocationsAndProperties()
    {
        // Crafted to exceed the default threshold (15) while hitting every
        // reason-string variant the metric emits:
        //   if @ nesting 0  → "+1"
        //   if @ nesting 1..4 → "+N (incl M for nesting)"
        //   recursive M(b) → "+1 (recursion)"
        // Score: 1 + 2 + 3 + 4 + 5 + 1 + 1 + 1 = 18.
        const string source = """
            class C
            {
                int M(bool b)
                {
                    if (b)
                    {
                        if (b)
                        {
                            if (b)
                            {
                                if (b)
                                {
                                    if (b)
                                    {
                                        return M(b);
                                    }
                                }
                            }
                        }
                    }
                    if (b) { }
                    if (b) { }
                    if (b) { }
                    return 0;
                }
            }
            """;

        var diagnostic = await RunAnalyzerAsync(source);

        var countRaw = diagnostic.Properties["increment.count"];
        Assert.NotNull(countRaw);
        var count = int.Parse(countRaw!, System.Globalization.CultureInfo.InvariantCulture);

        Assert.Equal(count, diagnostic.AdditionalLocations.Count);
        Assert.True(count >= 3, $"expected at least 3 increments, got {count}");

        var reasons = Enumerable.Range(0, count)
            .Select(i => diagnostic.Properties[$"increment.{i}.reason"])
            .ToList();

        Assert.Contains("+1", reasons);
        Assert.Contains(reasons, r => r is not null && r.Contains("incl ") && r.Contains(" for nesting"));
        Assert.Contains("+1 (recursion)", reasons);

        foreach (var location in diagnostic.AdditionalLocations)
        {
            Assert.True(location.IsInSource);
            Assert.True(location.SourceSpan.Length >= 0);
        }
    }

    /// <summary>
    /// The property threshold (default 3) is intentionally much smaller than
    /// the method threshold (default 15). A body that would be silent on a
    /// method must fire PARL3001 when embedded in a property arrow body,
    /// indexer arrow body, or any accessor — the whole point of the split.
    /// </summary>
    [Theory]
    [InlineData("PropertyArrow", """
        class C
        {
            private bool _a, _b, _c, _d;
            public int P => (_a && _b) || (_c && _d) ? 1 : 0;
        }
        """, "P")]
    [InlineData("IndexerArrow", """
        class C
        {
            private bool _a, _b, _c, _d;
            public int this[int i] => (_a && _b) || (_c && _d) ? 1 : 0;
        }
        """, "this[]")]
    [InlineData("GetAccessor", """
        class C
        {
            private bool _a, _b, _c, _d;
            public int P
            {
                get
                {
                    if (_a && _b) return 1;
                    if (_c && _d) return 2;
                    return 0;
                }
            }
        }
        """, "P.get")]
    [InlineData("SetAccessor", """
        class C
        {
            private bool _a, _b, _c, _d;
            private int _p;
            public int P
            {
                get => _p;
                set
                {
                    if (_a && _b) _p = value;
                    else if (_c && _d) _p = -value;
                    else _p = 0;
                }
            }
        }
        """, "P.set")]
    [InlineData("InitAccessor", """
        class C
        {
            private bool _a, _b, _c, _d;
            private int _p;
            public int P
            {
                get => _p;
                init
                {
                    if (_a && _b) _p = value;
                    else if (_c && _d) _p = -value;
                    else _p = 0;
                }
            }
        }
        """, "P.init")]
    [InlineData("AddAccessor", """
        using System;
        class C
        {
            private bool _a, _b, _c, _d;
            private EventHandler _h;
            public event EventHandler E
            {
                add
                {
                    if (_a && _b) _h += value;
                    else if (_c && _d) _h = value;
                    else _h = null;
                }
                remove => _h -= value;
            }
        }
        """, "E.add")]
    [InlineData("RemoveAccessor", """
        using System;
        class C
        {
            private bool _a, _b, _c, _d;
            private EventHandler _h;
            public event EventHandler E
            {
                add => _h += value;
                remove
                {
                    if (_a && _b) _h -= value;
                    else if (_c && _d) _h = null;
                    else _h = null;
                }
            }
        }
        """, "E.remove")]
    public async Task Reports_WhenPropertyShapedDeclarationExceedsPropertyThreshold(
        string scenario, string source, string expectedName)
    {
        _ = scenario;

        var diagnostic = await RunAnalyzerAsync(source);

        Assert.Equal(PARL3001_CognitiveComplexityThreshold.DiagnosticId, diagnostic.Id);
        Assert.Equal(expectedName, diagnostic.GetMessage()!.Split('\'')[1]);
    }

    [Fact]
    public async Task NoDiagnostic_WhenSameBodyOnMethodStaysUnderMethodThreshold()
    {
        // Regression guard for the dual-threshold split: a body that fires on
        // a property (score 4, threshold 3) must stay silent on a method
        // (score 4, threshold 15). Any regression that wired method kinds
        // through the property threshold would make this method fire.
        const string source = """
            class C
            {
                private bool _a, _b, _c, _d;
                public int M() => (_a && _b) || (_c && _d) ? 1 : 0;
            }
            """;

        await Verify.VerifyAnalyzerAsync(source);
    }

    /// <summary>
    /// Non-static local functions fold into their containing declaration's
    /// score. Reporting them as independent analysis targets would double-count
    /// their body (once in the parent's score, once on their own) — so the
    /// analyzer must emit a single diagnostic on the parent, not one on the
    /// parent and another on the local. This guards the scoping split
    /// documented in the PARL3001 contract against regressions where the
    /// LocalFunctionStatement registration forgets to skip non-static locals.
    /// </summary>
    [Fact]
    public async Task NonStaticLocalFunction_IsFoldedIntoParent_NotReportedIndependently()
    {
        // 20 sequential `if`s in the local: standalone score 20 (would fire
        // PARL3001 on its own under the buggy dual-report behavior). Folded
        // into the parent at nesting 1 each `if` scores +2 → parent's score
        // is 40, comfortably over the 15 threshold. The fix makes this method
        // produce exactly one diagnostic, on M.
        const string source = """
            class C
            {
                void M(bool b)
                {
                    void Local()
                    {
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                    }

                    Local();
                }
            }
            """;

        var diagnostics = await RunAnalyzerAllAsync(source);

        var diagnostic = Assert.Single(diagnostics);
        Assert.Contains("'M'", diagnostic.GetMessage());
    }

    /// <summary>
    /// Static local functions are scored independently: the parent's score
    /// excludes the static body, and the diagnostic (if any) fires on the
    /// local itself. This test sits opposite the non-static case above so the
    /// two scoping rules are pinned down by analyzer-level coverage, not just
    /// by the metric's unit tests.
    /// </summary>
    [Fact]
    public async Task StaticLocalFunction_ReportsItself_ParentStaysSilent()
    {
        // Same 20-if body, but `static`. Parent's score excludes the body
        // entirely, so M scores 0. The static local's standalone score is 20,
        // over the 15 threshold — exactly one diagnostic, on Local.
        const string source = """
            class C
            {
                void M(bool b)
                {
                    static void Local(bool b)
                    {
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                        if (b) { }
                    }

                    Local(b);
                }
            }
            """;

        var diagnostics = await RunAnalyzerAllAsync(source);

        var diagnostic = Assert.Single(diagnostics);
        Assert.Contains("'Local'", diagnostic.GetMessage());
    }

    private static async Task<Diagnostic> RunAnalyzerAsync(string source)
    {
        var diagnostics = await RunAnalyzerAllAsync(source);
        return diagnostics.Single();
    }

    private static async Task<ImmutableArray<Diagnostic>> RunAnalyzerAllAsync(string source)
    {
        var tree = CSharpSyntaxTree.ParseText(source);
        var compilation = CSharpCompilation.Create(
            "EncodingTest",
            [tree],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(new PARL3001_CognitiveComplexityThreshold());
        var withAnalyzers = compilation.WithAnalyzers(analyzers);
        var diagnostics = await withAnalyzers.GetAnalyzerDiagnosticsAsync();

        return [.. diagnostics.Where(d => d.Id == PARL3001_CognitiveComplexityThreshold.DiagnosticId)];
    }
}
